### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by sicko-gl** [glftpd/f-ftpbnc#3]
f-ftpbnc does not compile on Ubuntu 16.04:
$ unzip master.zip
Archive:  master.zip
c99893ebb572887b210119ea586fa5ffafe3dd45
   creating: f-ftpbnc-master/
  inflating: f-ftpbnc-master/.gitignore
  inflating: f-ftpbnc-master/Makefile
  inflating: f-ftpbnc-master/README.md
  inflating: f-ftpbnc-master/f-ftpbnc.c
  inflating: f-ftpbnc-master/f-ftpbnc.h
  inflating: f-ftpbnc-master/hsscript.nfo
  inflating: f-ftpbnc-master/mkconfig.c
  inflating: f-ftpbnc-master/sha256.c
  inflating: f-ftpbnc-master/sha256.h
  inflating: f-ftpbnc-master/xtea-cipher.h
$ cd f-ftpbnc-master/
$ make
cc -W -Wall -g -c -o mkconfig.o mkconfig.c
cc -W -Wall -g -c -o sha256.o sha256.c
cc -W -Wall -g  -o mkconfig mkconfig.o sha256.o
mkconfig.o: In function `xtea_cbc_encipher':
/tmp/f-ftpbnc-master/xtea-cipher.h:59: undefined reference to `xtea_cbc_copy'
/tmp/f-ftpbnc-master/xtea-cipher.h:62: undefined reference to `xtea_cbc_xor'
/tmp/f-ftpbnc-master/xtea-cipher.h:64: undefined reference to `xtea_cbc_copy'
mkconfig.o: In function `xtea_cbc_decipher':
/tmp/f-ftpbnc-master/xtea-cipher.h:74: undefined reference to `xtea_cbc_copy'
/tmp/f-ftpbnc-master/xtea-cipher.h:77: undefined reference to `xtea_cbc_copy'
/tmp/f-ftpbnc-master/xtea-cipher.h:79: undefined reference to `xtea_cbc_xor'
/tmp/f-ftpbnc-master/xtea-cipher.h:80: undefined reference to `xtea_cbc_copy'
collect2: error: ld returned 1 exit status
Makefile:33: recipe for target 'mkconfig' failed
make: *** [mkconfig] Error 1
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

**Comment by scriptzteam** [comment]
got error too on 16.10

```
cc -W -Wall -g   -o f-ftpbnc f-ftpbnc.o sha256.o
f-ftpbnc.o: In function `xtea_cbc_encipher':
/root/ftpbnc/xtea-cipher.h:59: undefined reference to `xtea_cbc_copy'
/root/ftpbnc/xtea-cipher.h:62: undefined reference to `xtea_cbc_xor'
/root/ftpbnc/xtea-cipher.h:64: undefined reference to `xtea_cbc_copy'
f-ftpbnc.o: In function `xtea_cbc_decipher':
/root/ftpbnc/xtea-cipher.h:74: undefined reference to `xtea_cbc_copy'
/root/ftpbnc/xtea-cipher.h:77: undefined reference to `xtea_cbc_copy'
/root/ftpbnc/xtea-cipher.h:79: undefined reference to `xtea_cbc_xor'
/root/ftpbnc/xtea-cipher.h:80: undefined reference to `xtea_cbc_copy'
f-ftpbnc.o: In function `socket_close':
/root/ftpbnc/f-ftpbnc.c:705: undefined reference to `membuff_free'
/root/ftpbnc/f-ftpbnc.c:706: undefined reference to `membuff_free'
f-ftpbnc.o: In function `sockethandler_membuffsend':
/root/ftpbnc/f-ftpbnc.c:736: undefined reference to `membuff_top'
/root/ftpbnc/f-ftpbnc.c:747: undefined reference to `membuff_gobble'
/root/ftpbnc/f-ftpbnc.c:733: undefined reference to `membuff_available'
f-ftpbnc.o: In function `needwrite_membuff':
/root/ftpbnc/f-ftpbnc.c:757: undefined reference to `membuff_available'
f-ftpbnc.o: In function `socket_write':
/root/ftpbnc/f-ftpbnc.c:768: undefined reference to `membuff_available'
f-ftpbnc.o: In function `socket_flushident':
/root/ftpbnc/f-ftpbnc.c:827: undefined reference to `membuff_top'
/root/ftpbnc/f-ftpbnc.c:835: undefined reference to `membuff_gobble'
/root/ftpbnc/f-ftpbnc.c:824: undefined reference to `membuff_available'
collect2: error: ld returned 1 exit status
Makefile:32: recipe for target 'f-ftpbnc' failed
make: *** [f-ftpbnc] Error 1
```

**Comment by scriptzteam** [comment]
@sicko-gl use ours, it is working ;)

https://github.com/scriptzteam/ftpBNC.v1.0---sCRiPTz-TEAM

**Comment by sicko-gl** [comment]
On Sun, 6 Nov 2016, [sCRiPTz-TEAM] wrote:

> 
> @sicko-gl use ours, it is working ;)
> 
> https://github.com/scriptzteam/ftpBNC.v1.0---sCRiPTz-TEAM

Is this a fork or new code?

**Comment by h-0-s-h** [comment]
Looks newer.
Mine is fork + fixes waiting for merge:
https://github.com/glftpd/f-ftpbnc/pull/4
